imports:
    - { resource: ../../../../../*/Infrastructure/Configuration/ApiPlatform/mapping.yaml }

api_platform:
    title: Hello API Platform
    version: 1.0.0
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
