framework:
    validation:
        email_validation_mode: html5
        mapping:
            paths:
                - '%kernel.project_dir%/src/Transaction/Infrastructure/Configuration/Symfony/validation'
