kernel:
    resource: ../src/Shared/Infrastructure/Symfony/Kernel.php
    type: annotation

app:
    resource: ../src/*/Infrastructure/Configuration/Symfony/Route/*
        
when@dev:
    app:
        resource: ../src/*/Infrastructure/Configuration/Symfony/Route/dev/*
